version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --no-input --clear && gunicorn --bind 0.0.0.0:8080 --worker-class gevent --access-logfile - --error-logfile - --workers 2 library.wsgi"
    # command:
    # command: docker-compose exec web python manage.py migrate --noinput
    volumes:
      - static_volume:/home/app/web/staticfiles
    deploy:
      replicas: 3
    expose:
      - 8080
    env_file:
      - ./.env.prod
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  # reverse-proxy and static file serving
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:80

volumes:
  postgres_data:
  static_volume:
