# Generated by Django 3.2.7 on 2021-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_chapter_numeral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
