# Generated by Django 3.2.8 on 2021-10-10 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snippets", "0002_auto_20211010_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="highlighted",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
