name: Development

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1
      - name: Install dependencies
        run: poetry install
      - name: Type-check
        run: poetry run pyright
      - name: Tests
        run: echo todo
